[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "4Qo6zT3LNsVM4msHUa3vKAhyMK4PtjT74RLdhYDnVeDu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jdnichollsc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
